"""init tables

Revision ID: 384c986e6d84
Revises: 
Create Date: 2026-06-24 17:27:15.074177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '384c986e6d84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casino_games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('game_code', sa.String(length=100), nullable=False),
    sa.Column('desktop_id', sa.String(length=100), nullable=True),
    sa.Column('mobile_id', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('game_image', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('highlights', sa.Boolean(), nullable=False),
    sa.Column('highlight_order', sa.Integer(), nullable=True),
    sa.Column('news', sa.String(length=10), nullable=True),
    sa.Column('news_order', sa.Integer(), nullable=True),
    sa.Column('on_the_rise', sa.String(length=10), nullable=True),
    sa.Column('on_the_rise_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_code')
    )
    op.create_table('sport_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enet_code', sa.String(length=50), nullable=False),
    sa.Column('sport_type', sa.String(length=30), nullable=False),
    sa.Column('championship', sa.String(length=150), nullable=True),
    sa.Column('championship_en', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_en', sa.String(length=100), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('out_team', sa.String(length=100), nullable=True),
    sa.Column('home_coats_of_arms', sa.Text(), nullable=True),
    sa.Column('out_coats_of_arms', sa.Text(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('played_time', sa.String(length=10), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valid_odds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enet_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('credits', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('casino_credits', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sports_bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('retained_credit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('pix_key', sa.String(length=150), nullable=True),
    sa.Column('pix_key_type', sa.String(length=30), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('break_period_end', sa.DateTime(), nullable=True),
    sa.Column('self_excluded', sa.Boolean(), nullable=False),
    sa.Column('notification_sms', sa.Boolean(), nullable=False),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('return_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('extracted_quotation', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('free_bet', sa.Boolean(), nullable=False),
    sa.Column('spend_from', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('accept_all_changes', sa.Boolean(), nullable=False),
    sa.Column('only_accept_high', sa.Boolean(), nullable=False),
    sa.Column('qtt_sports', sa.Integer(), nullable=False),
    sa.Column('qtt_open_sports', sa.Integer(), nullable=False),
    sa.Column('cashoutable', sa.Boolean(), nullable=False),
    sa.Column('cashout_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mobile', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('markets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_pt', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('specifier', sa.String(length=100), nullable=True),
    sa.Column('has_specifiers', sa.Boolean(), nullable=False),
    sa.Column('status_change_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sport_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('bonus_type', sa.String(length=50), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('qr_code_image', sa.Text(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bet_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('enet_code', sa.String(length=50), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('odd_id', sa.String(length=100), nullable=False),
    sa.Column('option_id', sa.String(length=50), nullable=False),
    sa.Column('quotation', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('specifier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('previous_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['sport_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('odd_id', sa.String(length=100), nullable=False),
    sa.Column('option_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('prev_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('hash', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['sport_events.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odds')
    op.drop_table('bet_items')
    op.drop_table('transactions')
    op.drop_table('markets')
    op.drop_table('bets')
    op.drop_table('users')
    op.drop_table('sport_events')
    op.drop_table('casino_games')
    # ### end Alembic commands ###
